#include "suites\CudaMathTests.h"
#include "suites\CudaMat2Tests.h"
#include "suites\CudaMat3Tests.h"
#include "suites\CudaMat4Tests.h"
#include "suites\CudaVecTests.h"
#include "suites\CudaTracableTests.h"
#include "suites\IOTests.h"
#include "suites\CudaVectorTests.h"
#include "suites\DeviceObjectTests.h"
//#include "suites\CudaBIH2DTests.h"

